### ISSUE TITLE
script/console gives OAuth2::HTTPError: Received HTTP 500 during request.

### ISSUE THREAD

**Issue by gabrielhase** [nsanta/fbgraph#1]
In my rails app everything works fine, but when trying the exact same code in script/console I get the following error on each request to facebook.

**Comment by nsanta** [comment]
Gabriel: I will take a look soon. Thanks for the report.

**Comment by duvalls** [comment]
this was working fine. But now fails (FB is changing stuff again ?!?)
when I do the login, fb gives me a stupid msg: An error occurred. Please try again later. I
is FB fubar ?  or does the gem need to play catchup?

**Comment by nsanta** [comment]
I tested the gem yesterday publishing a feed on my wall and getting info from my friends with success. Can you provide an example?

Thanks

**Comment by joren** [comment]
I get this error, even in the browser, when I try to upload a photo to my profile

<pre>
client.selection.user(self.user_id).photos.publish!(:source => data[:photo], :message => data[:caption])
</pre>


<pre>
OAuth2::HTTPError in Post/photosController#create

Received HTTP 500 during request.
</pre>

**Comment by nsanta** [comment]
ok, i will take a look into it soon.

**Comment by nsanta** [comment]
@joren: The problem is that Oauth2 uses Faraday as a Rest client with Yajl. Yajl doesn't support multipart form-data enctype as i see. I'm working on a driver of curb for Faraday that will resolve this problem.

**Comment by nsanta** [comment]
Solved on version 0.1.4
