### ISSUE TITLE
Problem with the picture url

### ISSUE THREAD

**Issue by nielsjansendk** [nsanta/fbgraph#15]
Hi again

There is the problem with the url for the profile picture. This is the line i use to get the picture url:

client.selection.me.picture

And this is the url I get:

https://graph.facebook.comme/picture?access_token=whatever

Clearly there is a / missing between .com and me.

:-)

Nina

**Comment by nielsjansendk** [comment]
Oh, and it adds the access-token twice so the url doesn't work....

**Comment by nsanta** [comment]
fixed on last version
