### ISSUE TITLE
Possibility to specify locale parameter to get user gender in a specified locale

### ISSUE THREAD

**Issue by Florent2** [nsanta/fbgraph#20]
Hi Nicolas,

By default the Facebook API does return the user gender attribute in the user locale ('hombre' for example)... making quite hard to deal with those values when the users come from different countries.

Looks like it's possible for force a locale when requesting the Facebook API to always get such attributes in a specified locale. I could not find a specific reference to that in the Facebook API documentation, but several posts mention it, for instance http://forum.developers.facebook.net/viewtopic.php?pid=174065

Do you think it would possible to add an option in fbgraph to force a locale when requesting the Facebook Graph API?

Florent

**Comment by nsanta** [comment]
As Far As I know, there is no possible way to do that. 

I will keep this issue open, so if someone knows how to provide a solve, has the possibility write down it as a comment.

**Comment by nsanta** [comment]
i found the solution
you need to pass as a extra parameter the locale type.

Example:

> facebook_client.selection.me.params({:locale => 'es_ES'}).info!

If you want to test, go to http://developers.facebook.com/docs/api and click on the User example (Users: https://graph.facebook.com/btaylor (Bret Taylor)), after that forge the url and append "&locale=es_ES".
