### ISSUE TITLE
FQL queries

### ISSUE THREAD

**Issue by joren** [nsanta/fbgraph#27]
Is there a fast way to get fql queries in the plugin?
Like in https://github.com/appoxy/mini_fb

**Comment by nsanta** [comment]
This gem is a wrapper of Open Graph API, not a wrapper of the old a deprecated REST API. 
I will not integrate deprecations.

Tip: you can call fql queries with the Facebook Javascript API, which "improves"  the performance on  server side running the query on the client side ;).

**Comment by nsanta** [comment]
@joren I added support for FQL on master (As well as for timeline actions)
