### ISSUE TITLE
Can't load config from YAML?

### ISSUE THREAD

**Issue by nswarr** [nsanta/fbgraph#28]
I'm using Rails 3 on Ruby 1.8.7.  I created facebook.yml and put it in the config folder.  It doesn't get loaded.  Based on what I'm reading in the code, it doesn't look like it ever will.  

In the FbGraph module, the choice to grab the config is in the config method,
    def config
      @config ||= load_config(File.join(Rails.root , 'config' , 'facebook.yml')).freeze
    end
But the @config member variable always has a value.  It's set as soon as the FbGraph module is parsed.
    @config = {}
The ||= never evaluates to loading the configuration.  When I change the code and remove the automatic initialization of @config, it still seemingly doesn't work.  This line from the Client initialization fails to get the config.
    @client_id, @secret_id = options[:client_id] || FBGraph.config[:client_id], options[:secret_id] || FBGraph.config[:secret_id]
FBGraph.config[:client_id] is evaluated as nil when using a label to retrieve the value of client_id.  Using the literal strings 'client_id' and 'secret_id' works to get the values.  After that, things are fine.

Have I missed something?

**Comment by mlightner** [comment]
Noticed this as well when moving from Ruby 1.8 to 1.9 just this past week, actually.

**Comment by nswarr** [comment]
Did this work for you at some point or did you just notice when doing the migration?

**Comment by nsanta** [comment]
fixed  on master.
