### ISSUE TITLE
selection without token

### ISSUE THREAD

**Issue by joren** [nsanta/fbgraph#3]
I can't do a selection when I'm not authenticated. If still need a consumer or I get this error:

<pre>
undefined method `get' for nil:NilClass
/Users/joren/.bundle/ruby/1.8/bundler/gems/rails/activesupport/lib/active_support/whiny_nil.rb:48:in `method_missing'
/Library/Ruby/Gems/1.8/gems/fbgraph-0.0.9/lib/fbgraph/base.rb:47:in `info!'
</pre>

I've created a client without a token because I don't need one to do a simple get like this:
http://graph.facebook.com/125467577971
But you need a token to create a consumer...

any ideas

**Comment by nsanta** [comment]
will be fixed in the next release

**Comment by joren** [comment]
awesome, thanks!

**Comment by nsanta** [comment]
joren: fixed on master branch

**Comment by nsanta** [comment]
close
