### ISSUE TITLE
"message": "Missing redirect_uri parameter."

### ISSUE THREAD

**Issue by mediazard** [nsanta/fbgraph#30]
Hello I'm using the code from your example, but 
I have this error during the redirection to the page of my app
{
   "error": {
      "type": "OAuthException",
      "message": "Missing redirect_uri parameter."
   }
}
Thanks

**Comment by nsanta** [comment]
what gem version are you using?

**Comment by mediazard** [comment]
the last one from repository , but I have already solved this problem, there were errors in routes file, now I have a new one : how can i see the friends of logged account? 
thanks a lot and sorry  for my English

**Comment by nsanta** [comment]
facebook_client.selection.me.friends.info!
