### ISSUE TITLE
depending rcov is not able to install on wondows

### ISSUE THREAD

**Issue by GuoYangguang** [nsanta/fbgraph#31]
it seems your gem is best for facebook app(i have looked over other fb gems) after reading the developer doc on facebook.But the depending rcov gem is not able to install on windows.while i don't want to reinstall ruby,can you tell us how to manage it?
The error is following:

ruby 1.9.2p0 (2010-08-18) [i386-mingw32]

C:\Users\gyg>f:

F:>cd ruby/gem

F:\ruby\gem>gem install rcov-0.9.9.gem
Building native extensions.  This could take a while...
ERROR:  Error installing rcov-0.9.9.gem:
        ERROR: Failed to build gem native extension.

C:/Ruby192/bin/ruby.exe extconf.rb
creating Makefile

make
'make' 不是内部或外部命令，也不是可运行的程序
或批处理文件。('is not internal or external command,also not a executable programm...')

Gem files will remain installed in C:/Ruby192/lib/ruby/gems/1.9.1/gems/rcov-0.9.9 for inspection.
Results logged to C:/Ruby192/lib/ruby/gems/1.9.1/gems/rcov-0.9.9/ext/rcovrt/gem_make.out

F:\ruby\gem>

**Comment by nsanta** [comment]
fixed, bumped a new version and pushed a new release as a gem.

**Comment by GuoYangguang** [comment]
wow,it is so quick.thanks.I would try it now.
