### ISSUE TITLE
(#324) Requires upload file

### ISSUE THREAD

**Issue by mediazard** [nsanta/fbgraph#33]
I have this error : "(#324) Requires upload file" 
whith this code
 {
 me = FbGraph::User.me(session[:access_token])
me.photo!(:name => "name", :source => "http://hd-wallpaper.org/wallpapers95/Realistic_Flaming_Guitar_Fire.jpg")

}

thanks

**Comment by nsanta** [comment]
:source param is used for upload files from local, not urls that contains files.

**Comment by nsanta** [comment]
Please take a look in the facebook API documentation

http://developers.facebook.com/docs/reference/api/
