### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by mediazard** [nsanta/fbgraph#34]
sorry for all of this questions , but without the documentation I can't understend a lot of things in your gem
this time I'm trying add the tags to a photo that I've created 

me = FbGraph::User.me(session[:access_token])
file = File.new(File.join('/Users', 'tod','Documents','nov.jpg'), 'r')
photo = me.photo!(:name => 'foto di prova', :source => file, :tags => ?)

thanks

**Comment by nsanta** [comment]
this documentation will help you on what paramters are required

http://developers.facebook.com/docs/reference/api/

**Comment by mediazard** [comment]
thank you , but I don't know how to pass all parameters , tags must be an array, with x, y cord and user id , right ? can you post me an example please ?

**Comment by nsanta** [comment]
The FB documentation is not clear on that specific parameter (tags). So i encourage to you in try and research yourself. If you have the answer, let us now!.

thanks-

**Comment by mediazard** [comment]
ook ... I will try 
thanks

**Comment by nsanta** [comment]
tags": {"data": [{"id": "xxxxxxxxxxxxxxx","name": "ABC DEF","x": 57.5,"y": 51.2963,"created_time": "2010-12-13T16:01:54+0000"},
{"id": "xxxxxxxxx","name": "LMN OPQ","x": 46.6667,"y": 47.4074,"created_time": 010-12-13T16:02:01+0000"}
]}

**Comment by mediazard** [comment]
thanks but I've already tryed that , and i have the error > "invalid parameters"
maybe it's must be something like this : [{:id=>session[:fbid]},{:x=>25},{:y=>25},{:name=>"name"}] ?
