### ISSUE TITLE
installing 1.6 on windows then deploying on server has json related problem

### ISSUE THREAD

**Issue by GuoYangguang** [nsanta/fbgraph#35]
hi
i have error like following deploying on server after install successfully on windows:

disk1/home/slugs/382819_57fdc91_0c4a-b8fa2bc3-0709-43c6-81cd-30963a36b0f3/mnt/.bundle/gems/ruby/1.8/gems/fbgraph-1.6.0/lib/fbgraph.rb:4:in `require': no such file to load -- json (LoadError)

i have try my best,but don't know how to make it work

**Comment by GuoYangguang** [comment]
locally installed well on my windows,but not able to deploy to heroku...

**Comment by nsanta** [comment]
Check the gem list available on heroku. If json gem (or another gem) is not present, just read the documention of how to add new gems on heroku.
