### ISSUE TITLE
Untitled

### ISSUE THREAD

**Issue by GuoYangguang** [nsanta/fbgraph#36]
i have error like following deploying on server after install successfully on my local windows:

disk1/home/slugs/382819_57fdc91_0c4a-b8fa2bc3-0709-43c6-81cd-30963a36b0f3/mnt/.bundle/gems/ruby/1.8/gems/fbgraph-1.6.0/lib/fbgraph.rb:4:in `require': no such file to load -- json (LoadError)

i have try my best,but don't know how to make it work.it is locally installed well on my windows,but not able to deploy to heroku...

**Comment by mlightner** [comment]
I have used fbgraph on heroku personally before with no problems.  Perhaps try adding gem "json" to your main application gemfile?

**Comment by GuoYangguang** [comment]
thanks.you are right,what's more, i commented out the joson windows version in Gemfile.lock.it starts to work.
