### ISSUE TITLE
Id not correct 

### ISSUE THREAD

**Issue by zimbabao** [nsanta/fbgraph#37]
client.selection.me.info!.id gives wrong output and i get the usual warning "Object#id will be deprecated; use Object#object_id"
client.selection.me.info!['id] gives correct 
pretty printing shows correct output.

ruby 1.8.7 (2010-01-10 patchlevel 249) [x86_64-linux]
Ubuntu 10.4
Linux r-desktop 2.6.35.4 #2 SMP Mon Sep 20 08:46:54 IST 2010 x86_64 GNU/Linux

**Comment by nsanta** [comment]
@zimbabao client.selection.me.info! returns a hash 
The only way to get the id is:
client.selection.me.info!['id]
