### ISSUE TITLE
facebook logo,not authorization screen

### ISSUE THREAD

**Issue by GuoYangguang** [nsanta/fbgraph#38]
I make sure the app is not authorized,go the the app page on facebook to authorize, finally the facebook logo is show with a link that says "go to facebook". Then if I click that logo or point my browser directly to https://graph.facebook.com/oauth/authorize?client_id=...&redirect_uri=http://www.example.com/oauth_redirect, I do get an authorization screen.It is so strange if it is because of the expired token(after reading one closed issue here).What's more,if i directly use the facebook api instead of fbgraph,the same problem happens. is it because the fb new api is still in development?

**Comment by nsanta** [comment]
Facebook Open Graph API is recent, they published this API as a stable version, but IMO, still in early beta state. There is a lot of bugs, bad responses, outages,etc.

**Comment by GuoYangguang** [comment]
thanks
