### ISSUE TITLE
use of accounts selection connection type with fbgraph

### ISSUE THREAD

**Issue by Florent2** [nsanta/fbgraph#4]
Is it possible to use fbgraph with the 'accounts' selection connection type? I want to get the Facebook page(s) the user administrates.

 I first build my fb client for a user who has given the permissions "offline_access" and "manage_pages", and I can get call client.selection.accounts. But when I try client.selection.accounts.info! I get a HTTP Bad Request error from Facebook Graph API.

Is it possible to use the info! method on the connection accounts to get the pages the user administrates? If so do I have to do anything special?

Here is a session in the console:

  # info! on me is working

> client.selection.me.info!
> FBGRAPH [GET]: /me
> warning: peer certificate won't be verified in this SSL session
>  => <#Hashie::Mash email="myemail@gmail.com" first_name="my first name" gender="hombre" id="100000849285906" last_name="my last name" link="http://www.facebook.com/profile.php?id=100000849285906" locale="en_US" name="my name" timezone=-5 updated_time="2010-03-12T00:18:15+0000" verified=true>

 # I can call accounts

> client.selection.accounts
>  => #<FBGraph::Selection:0x1027dd1a8 @connection_type="accounts", @params={}, @client=#<FBGraph::Client:0x102801030 @facebook_uri="https://graph.facebook.com", @client_id="134493806579275", @consumer=#<OAuth2::AccessToken:0x102800608 @token="134493806579275|826d99c877f4c0adaf6e9255-100000849285906|WycnKxc7AtVxmyTUwCYhMBccyn0.", @expires_in=nil, @client=#<OAuth2::Client:0x102800ec8 @options={}, @id="134493806579275", @site="https://graph.facebook.com", @connection=#<Faraday::Connection:0x102800e78 @options={}, @parallel_manager=nil, @builder=#<Faraday::Builder:0x102800928 @handlers=[#<Proc:0x0000000107ad2818@/Users/Florent/.rvm/gems/ree-1.8.7-2010.01/gems/faraday-0.4.6/lib/faraday/builder.rb:17>, #Proc:0x0000000107acda20@/Users/Florent/.rvm/gems/ree-1.8.7-2010.01/gems/faraday-0.4.6/lib/faraday/builder.rb:55]>, @path_prefix="/", @port=nil, @scheme="https", @ssl={}, @params={}, @headers={}, @host="graph.facebook.com">, @secret="94ee5db7e831af89e1f789dd4d81469b">, @refresh_token=nil>, @access_token="134493806579275|826d99c877f4c0adaf6e9255-100000849285906|WycnKxc7AtVxmyTUwCYhMBccyn0.", @secret_id="94ee5db7e831af89e1f789dd4d81469b">>

 # but I can't call info!

> client.selection.accounts.info!
> FBGRAPH [GET]: 
> warning: peer certificate won't be verified in this SSL session
> OAuth2::HTTPError: Received HTTP 400 during request.
>         from /Users/Florent/.rvm/gems/ree-1.8.7-2010.01/gems/oauth2-0.0.10/lib/oauth2/client.rb:70:in `request'
>         from /Users/Florent/.rvm/gems/ree-1.8.7-2010.01/gems/oauth2-0.0.10/lib/oauth2/access_token.rb:19:in`request'
>         from /Users/Florent/.rvm/gems/ree-1.8.7-2010.01/gems/oauth2-0.0.10/lib/oauth2/access_token.rb:23:in `get'
>         from /Users/Florent/.rvm/gems/ree-1.8.7-2010.01/bundler/gems/fbgraph-c1ffae2409fc4727c8b5aa7e6a1cf5f08ea9300d-master/lib/fbgraph/base.rb:47:in`info!'

**Comment by nsanta** [comment]
you should use

> client.me.accounts.info!

or

> client.user(user_id).accounts.info!

**Comment by Florent2** [comment]
¡Gracias Nicolas !

It works perfectly :)

**Comment by nsanta** [comment]
De nada. 

:D
