### ISSUE TITLE
Feed publish doesn't support picture

### ISSUE THREAD

**Issue by bvsatyaram** [nsanta/fbgraph#41]
client.selection.me.feed.publish!(<params>) is publishing everything but the picture.
Every param of the following call is published except for the picture:
fbclient.selection.me.feed.publish!(
  :message => "This is message"),
  :name => "title of the feed",
  :caption => "Caption of the feed",
  :description => "Description of the feed"
  :link => "<link to app>",
  :picture => '<picture url>',
  :actions => "{'name': 'Volunteer', 'link': '<app url>'}"
)

**Comment by nsanta** [comment]
Picture is supported on fbgraph. I'm currently using feed.publish! with picture as parameter.:picture accepts only a url as a value, not a File.
