### ISSUE TITLE
Getting 403 forbidden when posting to feed

### ISSUE THREAD

**Issue by metatroid** [nsanta/fbgraph#42]
I can retrieve information just fine, but cannot post 

<pre>client = FBGraph::Client.new(:client_id => 'id',   :secret_id => 'secret', :token => current_user.authorizations.find(:all, :conditions => { :provider => 'facebook' })[0]['token'])</pre>

Token is derived from omniauth, id and secret are taken from my app page on facebook

<pre>client.selection.me.feed.publish!(:message => 'test', :name => 'test')</pre>

results in:
 RestClient::Forbidden: 403 Forbidden

Any ideas?

Thanks

Edit: my omniauth access token was not granting me publish permissions, I modified that and now it's working.

**Comment by nsanta** [comment]
cool.

**Comment by reginato** [comment]
Where modified this permission?
