### ISSUE TITLE
inbox - 400 bad request

### ISSUE THREAD

**Issue by metatroid** [nsanta/fbgraph#43]
client.selection.me.inbox.info!

is this wrong?  it gives a 400 error

**Comment by nsanta** [comment]
you requested to the user the read_mailbox permission?.

**Comment by metatroid** [comment]
Yes, I have read_mailbox permission enabled, and have authorized access from the user by requesting a new token and accepting the permissions from the facebook auth screen

**Comment by metatroid** [comment]
my mistake, I had an issue where updating the token with facebook did not insert the new token into my database, so i'd been calling the old one.  It's resolved now.

thanks for the awesome gem

**Comment by nsanta** [comment]
Glad to hear that you solved the problem. Thanks to you for use the fbgraph gem.
