### ISSUE TITLE
No configured canvas_url causes the class to be unusable

### ISSUE THREAD

**Issue by TheEmpty** [nsanta/fbgraph#46]
Error:
    undefined method `[]' for false:FalseClass
    .bundle/gems/ruby/1.8/gems/fbgraph-1.7.1/lib/fbgraph/authorization.rb:10:in`authorize_url'

(only showing relevant lines below)
Auth 10:
    params = { :redirect_uri => FBGraph.config[:canvas_url] }.merge(params)

FBGraph.config
    load_config(File.join(Rails.root , 'config' , 'facebook.yml')).freeze

FBGraph.load_config
    return false unless File.exist?(yaml_file)

**Comment by nsanta** [comment]
fixed on master. Thanks to @pwnall. I will publish a new gem version today.
