### ISSUE TITLE
Does this work with Rails 3.0.5

### ISSUE THREAD

**Issue by jasdeepsingh** [nsanta/fbgraph#47]
I get an error on Rails 3.0.5 in 
OAuth_controller # Start
 that says:

You have a nil object when you didn't expect it!
You might have expected an instance of ActiveRecord::Base.
The error occurred while evaluating nil.[]

Probably, i havent setup my facebook.yml file correctly. May be i can help you with documenting this if you can tell me how to setup the facebook.yml file?

**Comment by TheEmpty** [comment]
you need to update it, this was a bug recently fixed. It's unrelated to your rails version.

**Comment by jasdeepsingh** [comment]
Have you updated the fbgraph example app? Because I was trying to run
that app on my local machine...

There are not much good Facebook graph plugins out there, so, I'll
probably contribute to this gem extensively.

Thanks!

Sent from my iPhone

On 2011-03-29, at 4:36 PM, TheEmpty
reply@reply.github.com
wrote:

**Comment by nsanta** [comment]
"Have you updated the fbgraph example app?": No, sorry. I will update it as soon as possible.

My apologizes

**Comment by jasdeepsingh** [comment]
No problem!! I'll eagerly wait for the update to the example app so that i can learn from the examples and start contributing....
