### ISSUE TITLE
NoMethodError (undefined method `[]' for false:FalseClass)

### ISSUE THREAD

**Issue by mhuggins** [nsanta/fbgraph#48]
When I implement the example code and try to access oauth#start, I end up with an error:

NoMethodError (undefined method `[]' for false:FalseClass):
  app/controllers/oauth_controller.rb:3:in `start'

Rendered /Library/Ruby/Gems/1.8/gems/actionpack-3.0.5/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.1ms)
Rendered /Library/Ruby/Gems/1.8/gems/actionpack-3.0.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (6.2ms)
Rendered /Library/Ruby/Gems/1.8/gems/actionpack-3.0.5/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (11.9ms)

**Comment by nsanta** [comment]
Please, paste a snippet of the start action that includes the fbgraph method called.

BTW: try update your gem.

**Comment by mhuggins** [comment]
I didn't realize how much the repository version had changed since the latest available gem.  I updated my project to retrieve the git version directly, and this fixed the error I was seeing.  I think it related to the canvas_url not being defined in my config, which I found in another error report.  I'll mark this as closed, though it would be great to have an updated non-git gem!
