### ISSUE TITLE
Publishing to a page feed as the page and not as the page owner

### ISSUE THREAD

**Issue by Florent2** [nsanta/fbgraph#5]
Hello,

Not sure if it's a fbgraph issue, or if I miss something using fbgraph...

With fbgraph I can publish a message to a page feed but it appears published by the page owner (I have his credentials) and not by the page itself. Here is how I do:

fbg_client = FBGraph::Client.new(:client_id => FACEBOOK_APP_ID, :secret_id => FACEBOOK_APP_SECRET, :token => user.facebook_token)
fbg_client.selection.page(business.facebook_page_id).feed.publish!(:message => message, :link => announcement_url, :name => "new message")

I now try to have the message posted published by the page itself instead of the page owner but I could not find a way to do this in the FBGraph API Post page (http://developers.facebook.com/docs/reference/api/post) and only found related bugs for the old Facebook REST API (http://bugs.developers.facebook.com/show_bug.cgi?id=8184, http://bugs.developers.facebook.com/show_bug.cgi?id=8691).

Is is possible to do it with fbgraph?

Any help appreciated :)

**Comment by nsanta** [comment]
There are two problems:
1- there is a bug on post anything (event feed, photo) on a page. We need to wait, arggh!!!.
2- You need to request the manage_page permissions, get the access token (through /me/accounts request: fb_client.selection.me.coneection('accounts').info!) of that page and use it for post something. Unfortunately, like i mention on the item 1, there is a bug on API.

**Comment by Florent2** [comment]
Finally I could post to a page feed as the page itself and not the page owner using as you suggested the page access token. Did not try to post event or photo, just a basic message, and it's working :)

Thanks a lot Nicolas for your answer and your help by email, much appreciated!

**Comment by nsanta** [comment]
Cool. For post events on pages we need to wait.
The ticket on FB (vote for it!): http://bugs.developers.facebook.com/show_bug.cgi?id=11725

**Comment by Florent2** [comment]
voted :)
