### ISSUE TITLE
Fails for some accounts

### ISSUE THREAD

**Issue by ghost** [nsanta/fbgraph#50]
I'm running Rails 2.3.8 and using gem version 0.0.9.  So I completely understand if you don't want to answer the following or feel compelled to laugh at me.  That said, a number of users have synced their FB accounts to our system and the following code was working just fine.  Recently, however, it only seems to be working for some of the users.

``` ruby
client = FBGraph::Client.new( :client_id => fb_key, :secret_id => fb_secret, :token => user_token )
sel = client.selection
sel.params=( { :fields => 'work,education,name,picture,link' } )
sel.me.info!
```

Running this code in IRB for a user for whom this code doesn't work, I get the following error:
OAuth2::HTTPError: Received HTTP 400 during request.

Any thoughts?

**Comment by nsanta** [comment]
upgrade the gem to the last version.

**Comment by ghost** [comment]
I'd love to - but thought the new gem only worked for Rails 3.  This project requires Rails 2 (at least for the foreseeable future).

**Comment by nsanta** [comment]
The gem has been built to be framework agnostic. Works on any framework.
