### ISSUE TITLE
TypeError in OauthsController#callback 

### ISSUE THREAD

**Issue by ghost** [nsanta/fbgraph#51]
I have a simple application in Rails 3.0.7 using only FB authentication methods provided by FBGraph gem (tested on current gem version and git version) and I recieve the following error:

<code> TypeError in OauthsController#callback
can't convert Hash into Integer
app/controllers/oauth_controller.rb:7:in `callback'</code>

My callback method is defined as follows:

<code> def callback
    access_token = client.authorization.process_callback(params[:code], :redirect_uri => 'http://localhost:3000/oauth/callback')
    session[:access_token] = access_token
    user_json = client.selection.me.info!
    # in reality you would at this point store the access_token.token value as well as 
    # any user info you wanted
    render :json => user_json
  end</code>

I get the same error when using example application linked in gem's readme file.

I'd be very grateful for any help regarding this issue. Thank you in advance.

**Comment by grumpit** [comment]
I am also having this problem, in the Rails 3.0.7 app I am working with as well as the example app.

**Comment by ghost** [comment]
Ok this issue is solved. For anyone having the same problem solution can be found at this address:
https://github.com/nsanta/fbgraph_example/issues/4#issuecomment-1391994
