### ISSUE TITLE
Error installing with bundler - typhoeus. Seems like it needs "libcurl"

### ISSUE THREAD

**Issue by VikVenkat** [nsanta/fbgraph#53]
I haven't come across this error before, but it looks like it might be an OAuth2 bug. I'm running win7 64 bit.

**Comment by nsanta** [comment]
Most of all servers runs linux. I'm a linux user and i don't have Win7. If you want to fork the project and provide a patch, i will merge the changes into the current version. thanks for your report

**Comment by nsanta** [comment]
i found this solution for install lubcurl under windows. http://beginrescue.blogspot.com/2010/07/installing-curb-with-ruby-191-in.html

**Comment by VikVenkat** [comment]
That solution installs successfully, but i still get the fail on Typhoeus. I've got ubuntu up now though, so will try there later. Thanks for your help on this.
