### ISSUE TITLE
Delete a comment

### ISSUE THREAD

**Issue by thb** [nsanta/fbgraph#6]
Hi,
Is it possible to delete a comment with fbgraph?

**Comment by nsanta** [comment]
Yes. Using the gem version you can delete the comment in this way:

> client.selection.find(comment_id).delete!

I will add comment method on selection. Thanks

**Comment by nsanta** [comment]
you can delete the comment using the branch master using the comment method instead of find.

> client.selection.comment(comment_id).delete!

**Comment by nsanta** [comment]
closed

**Comment by thb** [comment]
Ok, that what I had done on my system as a monkey patch. Thanks!
