### ISSUE TITLE
<FbGraph::Exception: Unparsable Response: > fb_graph - rails 3.2.2

### ISSUE THREAD

**Issue by jamesw** [nsanta/fbgraph#60]
The latest version of this gem now causes a <FbGraph::Exception: Unparsable Response: > fb_graph - rails 3.1.3 exception.
I have resolved this by reverting back to the previous version of the gem as per my answer here.

http://stackoverflow.com/questions/9636619/fbgraphexception-unparsable-response-fb-graph-rails-3-1-3/9640466#9640466

I have no idea what causes the problem but if it is of any help the code that causes this exception looks like this
[code]
      owner = FbGraph::User.me(FB_TOKEN)
      pages = owner.accounts
      page = pages.detect do |page|
        page.identifier == FB_PAGE_ID
      end
      page.feed!(
        :message => params[:message],
        :description => params[:description],
        :link => self.app_link
      )
[/code]

Obviously the FB_PAGE_ID and the FB_TOKEN are constants for my specific page and user on facebook

**Comment by cumpais** [comment]
same issue here.

**Comment by nsanta** [comment]
@jamesw @cumpais Your report is shows that you are using fb_graph gem, not fbgraph.

You should report this issue in this repo:

https://github.com/nov/fb_graph

**Comment by nsanta** [comment]
closing
