### ISSUE TITLE
undefined method `__request__' for class `Net::HTTP'

### ISSUE THREAD

**Issue by jonlaing** [nsanta/fbgraph#71]
Recently updated my gems while merging two branches together and got this error:

```
$ rake test --trace
rake aborted!
undefined method `__request__' for class `Net::HTTP'
/Users/******/.rvm/gems/ruby-1.9.3-p392@ftue_refactor/gems/fbgraph-1.10.0/lib/fbgraph/client.rb:75:in `<class:HTTP>'
```

I'm running `ruby-1.9.3-p392` and `rails 3.2.18` on Mac OSX 10.8.5. The code that's being pointed out is the following:

``` ruby
# :nodoc: undo the clusterfuck that rest-client has done
module Net
  class HTTP
    undef request
    alias request __request__  # <=====
  end
end
```

Did `__request__` exist in an old version of Net::HTTP or a newer? or something? Any ideas would be greatly appreciated. Thanks!

**Comment by dmorrow** [comment]
jonlaing - did you have any success getting past this issue?

**Comment by nsanta** [comment]
@jonlaing @dmorrow This issue has been fixed. A new gem has been release by @pwnall (Thank you Victor)

**Comment by dmorrow** [comment]
Thanks @nsanta & @pwnall  - much appreciated!
