### ISSUE TITLE
400 Error during process_callback

### ISSUE THREAD

**Issue by sgoodwin** [nsanta/fbgraph#8]
```
def get_client(token = nil)
      client = FBGraph::Client.new(:client_id => 'application_id_from_facebook',:secret_id =>'application_secret_from_facebook', :token=>token)
      return client
    end

    def authorize(code= nil)
      client = get_client
      puts "Using code: #{code}"
      access_token = client.authorization.process_callback(code, :redirect_uri => real_redirect_uri)

      puts access_token
    end
```

This is the code I'm using to handle the code provided by facebook's callback. When I get to the line that calls the process_callback method, I get a 400 error with no explanation of what's wrong. Am I doing something wrong?

**Comment by nsanta** [comment]
not sure. check if all parameters passed are right (code, app_id, app_secret, callback_url should be the same on the authorize request and process_callback request)

**Comment by sgoodwin** [comment]
The authorization request and process_callback request both use that same code to generate the client with the app_id and app_secret. Facebook provides an application_id, application_secret and api_key, which of these should I be using and where?

**Comment by nsanta** [comment]
see the fbgraph_example on oauth_controller.rb

http://github.com/nsanta/fbgraph_example

**Comment by sgoodwin** [comment]
Works now. I grabbed the wrong key apparently. Thanks!
